kind: ConfigMap
apiVersion: v1
metadata:
  name: reportportal-pr-jobs-upload-config
  namespace: devconsole-qe-upload
data:
  reportportal.url: 'https://reportportal-openshift-dev-console.apps.ocp-c1.prod.psi.redhat.com/'
  openshiftcijob.pr.gs: >-
    gs://origin-ci-test/pr-logs/pull/openshift_console/
  openshiftcijob.pr.job.directory: /pull-ci-openshift-console-master-e2e-gcp-console/  
  openshiftcijob.pr.artifacts.path: /artifacts/e2e-gcp-console/test/artifacts/gui_test_screenshots/  
  openshiftcijob.pr.url: >-
    https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_console/
  openshiftcijob.buildid: ''
  openshiftcijob.latestbuild.filename: latest-build.txt
  updatescript.url: https://raw.githubusercontent.com/The-Anton/ci-scripts/main/report-portal-upload/xml_update_and_zip.py
  reportportal.import.api.url: https://reportportal-openshift-dev-console.apps.ocp-c1.prod.psi.redhat.com/api/v1/console/launch/import