apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosmee-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: gosmee-client
  template:
    metadata:
      labels:
        app: gosmee-client
    spec:
      containers:
        - name: gosmeeclient-container
          image: ghcr.io/chmouel/gosmee:latest
          imagePullPolicy: IfNotPresent
          args: ["client", "https://hook.pipelinesascode.com/LfNjFneiytLi", "http://el-cel-eventlistener-no-filter.devconsole-qe-upload.svc.cluster.local:8080"]